Update jenkinsfile

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -1,10 +1,33 @@
+def clearStage = {
+  return {
+    stage('Cluster termination') {
+       echo 'I am in clear stage'
+    }
+  }
+}
+
 pipeline {
     agent any
     stages {
         stage('Welcome Step') {
             steps { 
-                echo 'Welcome to LambdaTest'
+                sh 'echo "Fail!"; exit 1'  
             }
         }
     }
+    post {  
+         always {  
+             echo 'This will always run'  
+         }  
+         success {  
+             echo 'This will run only if successful'  
+         }  
+         failure {  
+            script{
+               clearStage().call()
+               }
+            mail bcc: '', body: "<b>Example</b><br>Project: ${env.JOB_NAME} <br>Build Number: ${env.BUILD_NUMBER} <br> URL de build: ${env.BUILD_URL}", cc: '', charset: 'UTF-8', from: '', mimeType: 'text/html', replyTo: '', subject: "ERROR CI: Project name -> ${env.JOB_NAME}", to: "munendrahbti@gmail.com";  
+            echo 'I just sent the mail'
+         }  
+     }
 }
